(dp1
S'output'
p2
S"<class 'sqlite3.IntegrityError'> FOREIGN KEY constraint failed"
p3
sS'layer'
p4
S'/home/vedant/Desktop/web2py/applications/garden_2_may/controllers/restaurant.py'
p5
sS'code'
p6
S"# -*- coding: utf-8 -*-\nresponse.menu.append(['Homepage',False,URL('restaurant','index')])\nresponse.menu+=[['Manage Orders',False,URL('restaurant','manage_orders')],['Change Menu',False,URL('manage_menu')]]\n\ndef index():\n    return resauth.user_id\n\ndef user():\n    return dict(form=resauth())\n\n@resauth.requires_login()\ndef change_menu():\n    form=SQLFORM(db.dish)\n    if form.process().accepted:\n        response.flash='%s has been added to the menu' %(form.vars.name)\n    elif form.errors:\n        response.flash='Please correct the errors and try again'\n    return dict(form=form)\n\nresponse._vars=response._caller(user)\n"
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/vedant/Desktop/web2py/gluon/restricted.py", line 224, in restricted\n    exec ccode in environment\n  File "/home/vedant/Desktop/web2py/applications/garden_2_may/controllers/restaurant.py", line 20, in <module>\n  File "/home/vedant/Desktop/web2py/gluon/globals.py", line 393, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/vedant/Desktop/web2py/applications/garden_2_may/controllers/restaurant.py", line 9, in user\n    return dict(form=resauth())\n  File "/home/vedant/Desktop/web2py/gluon/tools.py", line 1442, in __call__\n    return getattr(self, args[0])()\n  File "/home/vedant/Desktop/web2py/gluon/tools.py", line 2758, in register\n    self.add_membership(group_id, form.vars.id)\n  File "/home/vedant/Desktop/web2py/gluon/tools.py", line 3577, in add_membership\n    id = membership.insert(group_id=group_id, user_id=user_id)\n  File "/home/vedant/Desktop/web2py/gluon/dal/objects.py", line 724, in insert\n    ret =  self._db._adapter.insert(self, self._listify(fields))\n  File "/home/vedant/Desktop/web2py/gluon/dal/adapters/base.py", line 715, in insert\n    raise e\nIntegrityError: FOREIGN KEY constraint failed\n'
p11
s.